---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Ensure Duplicati package is downloaded
  get_url:
    url: "{{ duplicati_download_url }}"
    dest: "{{ duplicati_download_dir }}"
  register: duplicati_download

# Setup/install tasks.
- name: Include RedHat installation tasks
  include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky' or ansible_os_family == 'AlmaLinux'

- name: Include Debian installation tasks
  include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Ensure systemd unit file is installed
  copy:
    dest: /etc/systemd/system/duplicati.service
    content: |
      [Unit]
      Description=Duplicati web-server
      After=network.target

      [Service]
      Nice=19
      IOSchedulingClass=idle
      EnvironmentFile=-/etc/default/duplicati
      ExecStart=/usr/bin/duplicati-server $DAEMON_OPTS
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Ensure Duplicati is configured to listen on all interfaces
  copy:
    dest: /etc/default/duplicati
    content: |
      Defaults for duplicati initscript
      # sourced by /etc/init.d/duplicati
      # installed at /etc/default/duplicati by the maintainer scripts

      #
      # This is a POSIX shell fragment
      #

      # Additional options that are passed to the Daemon.
      DAEMON_OPTS="--webservice-interface=any --webservice-port=8200 --portable-mode"

- name: Ensure Duplicati service is started and enabled
  service:
    name: duplicati
    enabled: true
    state: started
