---
# tasks file for duplicati

- name: Install Prerequisite Packages
  apt:
    name:
      - mono-devel
    state: present

- name: Check if Duplicati package is installed
  command: dpkg-query -W duplicati
  register: duplicati_package_check_deb
  failed_when: duplicati_package_check_deb.rc > 1
  changed_when: duplicati_package_check_deb.rc == 1

- name: Download duplicati_package
  get_url: 
    url="https://updates.duplicati.com/beta/duplicati_2.0.6.1-1_all.deb"
    dest="~/duplicati_2.0.6.1-1_all.deb"
  when: duplicati_package_check_deb.rc == 1

- name: Install duplicati_package
  apt: deb="~/duplicati_2.0.6.1-1_all.deb"
  when: duplicati_package_check_deb.rc == 1

- name: Create a systemd unit file to run duplicati
  copy:
    dest: /etc/systemd/system/duplicati.service
    content: |
      [Unit]
      Description=Duplicati web-server
      After=network.target

      [Service]
      Nice=19
      IOSchedulingClass=idle
      EnvironmentFile=-/etc/default/duplicati
      ExecStart=/usr/bin/duplicati-server $DAEMON_OPTS
      Restart=always

      [Install]
      WantedBy=multi-user.target

- name: Edit the duplicati config to listen on all interfaces
  copy:
    dest: /etc/default/duplicati
    content: |
      Defaults for duplicati initscript
      # sourced by /etc/init.d/duplicati
      # installed at /etc/default/duplicati by the maintainer scripts

      #
      # This is a POSIX shell fragment
      #

      # Additional options that are passed to the Daemon.
      DAEMON_OPTS="--webservice-interface=any --webservice-port=8200 --portable-mode"

- name: Start and enable the duplicati service
  service:
    name: duplicati
    enabled: true
    state: started