---
- name: Ensure dependencies are installed
  yum:
    name: "{{ duplicati_dependencies }}"
    state: present

- name: Check if the Duplicati package is already installed
  shell:
    cmd: rpm -q duplicati
  register: rpm_installed
  failed_when: false
  changed_when: false

- name: Ensure the Duplicati package is installed
  shell:
    # --nodeps is required to work around a missing dependency only used for
    # the system tray icon. See https://github.com/duplicati/duplicati/issues/3950
    cmd: rpm --install --force --nodeps "{{ duplicati_download.dest }}"
  when: (rpm_installed.rc != 0) or not (rpm_installed.stdout in duplicati_download.dest)
