---
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization.
#
# See: https://github.com/marketplace/actions/publish-ansible-role-to-galaxy
# See: https://github.com/ansible/galaxy/issues/46

name: Release
'on':
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  galaxy_import:
    name: Ansible Galaxy import
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip3 install ansible-core

      - name: Trigger a new Ansible Galaxy import
        run: >-
          ansible-galaxy role import -vvv
          --api-key ${{ secrets.GALAXY_API_KEY }}
          $(echo ${{ github.repository }} | awk -F/ '{print $1, $2}')
