---
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization.
#
# See: https://github.com/marketplace/actions/publish-ansible-role-to-galaxy
# See: https://github.com/ansible/galaxy/issues/46

name: Release
'on':
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  dist_sync:
    name: Sync dist branch
    runs-on: ubuntu-latest
    steps:
      - name: Set custom vars (as step outputs)
        id: custom_vars
        run: |-
          # assuming repo 'owner/ansible-role-rolename', set checkout_path = 'owner.rolename'
          echo "checkout_path=$(echo ${{ github.repository }} | sed -E 's|/[^/]*?-|.|')" >> "$GITHUB_OUTPUT"

      - name: Setup repo and token
        uses: actions/checkout@v4
        with:
          path: ${{ steps.custom_vars.checkout_path}}

      - name: Swtich to dist branch
        run: |-
          git fetch origin dist
          git switch dist

      - name: Checkout role-specific files at git ref
        run: |-
          git rm -r ./
          git fetch origin ${{ github.ref }}
          git checkout ${{ github.ref }} -- defaults/ meta/ tasks/ vars/ LICENSE README.md

      - name: Push the changes back to dist
        run: |-
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "${{ github.ref_name }} (${{ github.sha }})"
          git push origin dist

  galaxy_import:
    name: Ansible Galaxy import
    needs: dist_sync
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Ansible
        run: pip3 install ansible-core

      - name: Trigger a new import on Galaxy
        run: >-
          ansible-galaxy role import
          --api-key ${{ secrets.GALAXY_API_KEY }}
          --branch dist
          $(echo ${{ github.repository }} | awk -F/ '{print $1, $2}')
